### ISSUE TITLE
Support for Context management

### ISSUE THREAD

**Issue by mcanonic** [data-henrik/watson-conversation-tool#5]
Hi,
I really like your script but I am wondering if you can update with two features:
- it seems impossible to manage the context. I need to clear the context before any input message.
- How can I exit from a dialog? Just a Control+C?
thanks,
M

**Comment by mcanonic** [comment]
Please ignore the second point, my bad. It was writtent that CRTL+C works.

**Comment by data-henrik** [comment]
Context management would be great, also for my own scenarios. I am already in the design phase.

**Comment by data-henrik** [comment]
BTW: I am thinking of having a "context" file. The tool would write to and read from it. Between receiving the message from WCS and sending the next input, users if the tool could edit the file / the context (from another window or with an editor).
What do you think?

**Comment by mcanonic** [comment]
First of all, I'm not an expert on WCS: I'm just starting using it, so my suggestions could be questionable. AFAIK, your script keeps the context as happens when you use WCS from the browser. So, if the user needs context, your script is ok right now. The problem is when the user needs to reset the context after each message. From my point of view, an easy solution could be this one: once the script is started, the user has to reply to this question: "Do you want keep context during your test with dialog? [Y/n]". Yes is the default behaviour (if the user just types "return"): the script works as it does now. If No, after any message input, the context is reset (and the user is notified).  The "context file" that you suggested could be a new feature: I like your idea but from my point of you that is a more advance usage of your script (I have no idea how this file should be formatted). Summary: first just have a switch controlled by a question (context on/off) to the user, then "context file" for advanced users.

**Comment by data-henrik** [comment]
I implemented a simple solution. Take a look. It is quite powerful because you can persist the entire session context, take copies of it and resume it later on (a day later). It is also possible to reset or modify variables, including system variables.

**Comment by mcanonic** [comment]
Traceback (most recent call last):
  File "wctool.py", line 233, in <module>
    converse(parms.workspaceID)
  File "wctool.py", line 171, in converse
    with open(contextFile) as jsonFile:
IOError: [Errno 2] No such file or directory: 'session_context.json'

**Comment by data-henrik** [comment]
I made it safer. It expected a session_context.json, but that can be ignored.

**Comment by mcanonic** [comment]
It cannot be ignored for the script: it kicks me out ;)

**Comment by data-henrik** [comment]
Did you try the new version?

**Comment by mcanonic** [comment]
I was quite sure, but today I re-download the code and I do not kicked off. The point now is how can I reset the context before each message?

**Comment by data-henrik** [comment]
The "ignoring" is a debug message.

You can reset the context as (very briefly) described in the README. Open an editor and modify (save it back) `session_context.json` after the response is received and before submitting the next input message.

**Comment by mcanonic** [comment]
Sorry, not sure I get it.  Should I have to open session_context.json and cancel what is inside? And repeat this procedure for any dialog turn?

**Comment by data-henrik** [comment]
session_context.json holds ALL context metadata. That is system and user variables. With an editor you can add/change/delete your user variables, you could even change system variables like the conversation_id, dialog turns, whatever. It is quite powerful.

It is a JSON file, so using an editor with JSON support is recommended.

**Comment by mcanonic** [comment]
I see. In my case, since I do not want any context/var between any dialog turn, I think is faster exit from the app and re-run it. Thanks.

**Comment by data-henrik** [comment]
closing as implemented
