### ISSUE TITLE
Next_step not importing

### ISSUE THREAD

**Issue by dmehra01** [data-henrik/watson-conversation-tool#7]
While trying to make changes in the current workspace using the input json file using command : 
python wctool.py -u -id WORKSPACE_ID -intents -entities -dialog_nodes -counterexamples -i henriksWorkspace.json,
i am not able to import the next_step part of the nodes which is in json :  

"next_step": {
        "behavior": "jump_to",
        "selector": "body",
        "dialog_node": "node_16_1512316852835"
      },

Let me know how to do that using wctool

**Comment by data-henrik** [comment]
Is that an error or is the data missing? It could be that the Watson API has changed and it is possible to upload more data sections.

**Comment by dmehra01** [comment]
Dialogs are not getting fully imported while updating the workspace using the tool.
In other words, the "And finally" conditions are not getting changed while I am trying to import the workspace from local workspace.json using the tool.

![image](https://user-images.githubusercontent.com/35993490/35795145-41b1fa18-0a7e-11e8-8752-ec950d739d8a.png)

"And finally" is importing as "Wait for user response" but in the workspace.json it is "Skip user input".

Please help on this.

**Comment by data-henrik** [comment]
I checked the API: https://github.com/watson-developer-cloud/python-sdk/blob/master/watson_developer_cloud/conversation_v1.py
There are no additional parameters to what I am using. Are you using the latest API version in the config? Could you share details about that? If that is on the latest API version, could you attached a short sample I could use to reproduce?

**Comment by dmehra01** [comment]
Changed the API version to latest one and now same is working fine.
Thanks.

**Comment by data-henrik** [comment]
Great to know, also for other users. Thanks for testing and closing the issue!
